name: radix-web-console-pr
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Bootstrap
        shell: powershell
        run: |
          ./bootstrap.ps1
