name: radix-web-console-pr
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bootstrap
        shell: powershell
        env:
          BLOB_STORAGE_CONNECTION: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
          COSMOSDB_CONNECTION: ${{ secrets.COSMOSDB_CONNECTION_STRING }}
        run: |
          .\scripts\bootstrap.ps1
